# Generated by Django 5.2.8 on 2025-11-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
